[package]
name = "rart"
version = "0.1.0"
authors = ["Oj <oj@oojmed.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg = "0.6.0"
rand = "0.7.2"
noise = "0.5.1"
